// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl8rYMKtxsGnJnOaZcJaX3Xysw7z0lUtE',
    appId: '1:988064158191:web:1da2d2401d7e78937ba61a',
    messagingSenderId: '988064158191',
    projectId: 'cardit-9542f',
    authDomain: 'cardit-9542f.firebaseapp.com',
    storageBucket: 'cardit-9542f.appspot.com',
    measurementId: 'G-E1FVDM6RH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp6LqZkmCLdJdsT4dGYceK_HmSESic6uQ',
    appId: '1:988064158191:android:69d8258eb76d254e7ba61a',
    messagingSenderId: '988064158191',
    projectId: 'cardit-9542f',
    storageBucket: 'cardit-9542f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIHzxovclXIR21xTRvMjXEitv3cgAtpfk',
    appId: '1:988064158191:ios:da0572f41e6121a97ba61a',
    messagingSenderId: '988064158191',
    projectId: 'cardit-9542f',
    storageBucket: 'cardit-9542f.appspot.com',
    androidClientId: '988064158191-jsr38688oueltdnof44986it0bbhs3gt.apps.googleusercontent.com',
    iosClientId: '988064158191-5959bulq69jlfogahuvhua2gmq1k7sgb.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIHzxovclXIR21xTRvMjXEitv3cgAtpfk',
    appId: '1:988064158191:ios:da0572f41e6121a97ba61a',
    messagingSenderId: '988064158191',
    projectId: 'cardit-9542f',
    storageBucket: 'cardit-9542f.appspot.com',
    androidClientId: '988064158191-jsr38688oueltdnof44986it0bbhs3gt.apps.googleusercontent.com',
    iosClientId: '988064158191-5959bulq69jlfogahuvhua2gmq1k7sgb.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardit',
  );
}
